CREATE SEQUENCE s_message START WITH 1 INCREMENT BY 1;

CREATE TABLE message (
  message_id BIGINT NOT NULL PRIMARY KEY,
  sender VARCHAR(100) NOT NULL,
  content TEXT NOT NULL
);

ALTER TABLE message ADD COLUMN address VARCHAR(100);